name: Update README

on:
  schedule:
    - cron: "15 10-11 * * 1,3,5"
    - cron: "15 15-18 * * 1,3,5"
    - cron: "45 10-12 * * 2,4"
    - cron: "45 16-19 * * 2,4"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether to run
        run: |
          if [ $((RANDOM % 2)) -eq 0 ]; then
            echo "Skip today"
            exit 0
          fi

      - name: Random delay
      - run: sleep $(( RANDOM % 1800 ))

      - uses: actions/checkout@v2

      - name: Do the work
      - run: |
          date >> update-log.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add update-log.txt
          git commit -m "chore: daily update"
          git push
